/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xWFLbIrAc4I
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from "next/image"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"

import { ChartTooltipContent, ChartTooltip, ChartContainer } from "@/components/ui/chart"

export function Dashboard() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-muted/40">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <Link href="#" className="flex items-center gap-2 text-lg font-semibold sm:text-base mr-4" prefetch={false}>
          <FrameIcon className="w-6 h-6" />
          <span className="sr-only">Anomaly Detection Dashboard</span>
        </Link>
        <nav className="hidden font-medium sm:flex flex-row items-center gap-5 text-sm lg:gap-6">
          <Link href="#" className="font-bold" prefetch={false}>
            Dashboard
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Alerts
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Reports
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Settings
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="rounded-full ml-auto">
                <Image
                  src="/placeholder.svg"
                  width="32"
                  height="32"
                  className="rounded-full border"
                  alt="Avatar"
                  style={{ aspectRatio: "32/32", objectFit: "cover" }}
                />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1 flex flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="flex items-center justify-between">
          <div className="grid gap-1">
            <h1 className="text-2xl font-bold tracking-tight">Anomaly Detection Dashboard</h1>
            <p className="text-muted-foreground">Monitor the health of your cloud services in real-time.</p>
          </div>
          <Button>View Alerts</Button>
        </div>
        <div className="grid gap-4 md:grid-cols-4 md:w-[80%] mx-auto">
          {[
            { name: "Service A", status: "normal" },
            { name: "Service B", status: "warning" },
            { name: "Service C", status: "anomaly" },
            { name: "Service D", status: "normal" },
            { name: "Service E", status: "normal" },
            { name: "Service F", status: "warning" },
            {
              name: "Service G",
              status: "anomaly",
            },
            { name: "Service H", status: "normal" },
            { name: "Service I", status: "normal" },
            {
              name: "Service J",
              status: "warning",
            },
            { name: "Service K", status: "anomaly" },
            { name: "Service L", status: "normal" },
          ].map((service, index) => (
            <div
              key={index}
              className={`flex flex-col items-center justify-center p-4 rounded-lg aspect-square transition-colors ${
                service.status === "normal"
                  ? "bg-green-500/20 hover:bg-green-500/30"
                  : service.status === "warning"
                  ? "bg-yellow-500/20 hover:bg-yellow-500/30"
                  : "bg-red-500/20 hover:bg-red-500/30"
              }`}
            >
              <div className="text-2xl font-bold">{service.name}</div>
              <div
                className={`text-sm font-medium ${
                  service.status === "normal"
                    ? "text-green-500"
                    : service.status === "warning"
                    ? "text-yellow-500"
                    : "text-red-500"
                }`}
              >
                {service.status.toUpperCase()}
              </div>
              <h1>Graph here</h1>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}


function FrameIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  )
}


function LinechartChart(_props: any) {
  return (
    <h3>Your Chart here</h3>
  )
}
